root: true
env:
  node: true
parserOptions:
  parser: babel-eslint
  ecmaVersion: 5
  ecmaFeatures:
    legacyDecorators: true
extends:
#  - airbnb-base
  - prettier
  - plugin:import/errors
  - plugin:import/warnings
globals:
  console: true
  jQuery: true
  $: true
  window: true
  document: true
  Vue: true
  axios: true,
  HTMLElement: true,
  Config: true,
  Mix: true,
rules:
  quotes:
    - error
    - single
  no-param-reassign:
    - 2
    - props: false
  strict: 0
  no-unused-expressions: 0
  no-underscore-dangle: 0
  class-methods-use-this: 0
  no-unused-vars:
    - error
    - argsIgnorePattern: '^h$'
settings:
  import/resolver: webpack
